name: Build Auditoria Kafka

on:
  push:
    paths:
      - 'auditoria/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v3

      - name: Login en Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build y Push de imagen
        uses: docker/build-push-action@v4
        with:
          context: ./auditoria
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/auditoria-kafka:latest