name: Deploy Infraestructura Kafka

on:
  push:
    paths:
      - 'terraform/**'
  workflow_run:
    workflows: ["Build Gateway Kafka", "Build Auditoria Kafka"]
    types: [completed]

jobs:
  terraform:
    name: 'Terraform Deploy'
    runs-on: ubuntu-latest
    # Se ejecuta si el push fue en la carpeta terraform o si los builds terminaron con Ã©xito
    if: ${{ github.event_name == 'push' || github.event.workflow_run.conclusion == 'success' }}
    
    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v3

      - name: Configurar Terraform
        uses: hashicorp/setup-terraform@v2

      # El init requiere las credenciales para acceder al bucket del backend S3
      - name: Terraform Init
        id: init
        run: terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

      # El apply requiere las credenciales para crear los recursos en AWS
      - name: Terraform Apply
        id: apply
        run: |
          terraform apply -auto-approve \
            -var="ssh_key_name=${{ secrets.SSH_KEY_NAME }}" \
            -var="docker_user=${{ secrets.DOCKER_USERNAME }}" \
            -var="aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" \
            -var="aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
            -var="aws_session_token=${{ secrets.AWS_SESSION_TOKEN }}"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}